version: '3.3'
services:
  
  nodered:
    image: docker-activage.satrd.es/activage-nr-service-composition:0.0.3-auth
    ports:
      - "1880:1880"
    expose:
        - "1880"
    restart: unless-stopped
    environment:
            - KEYCLOAK_HOST=${BASE_URL_PROTOCOL}://${AIOTES_HOSTNAME}:${AIOTES_API_PORT}
            - KEYCLOAK_REALM=${KEYCLOAK_REALM}
            - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
            - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
            - KEYCLOAK_AUTH_URL=${KEYCLOAK_HOST}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth
            - KEYCLOAK_TOKEN_URL=${KEYCLOAK_HOST}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
            - KEYCLOAK_USER_INFO_URL=${KEYCLOAK_HOST}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/userinfo
            - KEYCLOAK_CALLBACK_URL=${BASE_URL_PROTOCOL}://${AIOTES_HOSTNAME}:${AIOTES_API_PORT}/development/servicecomposer/auth/strategy/callback

networks:
  default:
    external:
      name: aiotes

